<?php

namespace Database\Seeders;

use App\Models\Satker;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SatkerSatwilSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable FK checks for truncate
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Satker::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // ── DATA SATKER ──────────────────────────────────────────
        $dataSatker = <<<'TXT'
ITWASDA
1	SUBBAGRENMIN
2	SUBBAGDUMASANWAS

BIRO OPS
1	SUBBAGRENMIN
2	BAGBINOPS
3	BAGDALOPS
4	BAGKERMA

BIRO RENA
1	SUBBAGRENMIN
2	BAGSTRAJEMEN
3	BAGRENPROGAR
4	BAGDALPROGAR
5	BAG RBP

BIRO SDM
1	SUBBAGRENMIN
2	BAGDALPERS
3	BAGBINKAR
4	BAGWATPERS
5	BAGPSI

BIRO LOG
1	SUBBAGRENMIN
2	BAGADA
3	BAGINFOLOG
4	BAGBEKUM
5	BAGPAL
6	BAGFASKON
7	URGUDANG

BIDHUMAS
1	SUBBAGRENMIN
2	SUBBIDPENMAS
3	SUBBID PID
4	SUBBIDMULMED

BIDPROPAM
1	SUBBAGRENMIN
2	SUBBAGYANDUAN
3	SUBBAGREHABPERS
4	SUBBIDPAMINAL
5	SUBBIDPROVOS
6	SUBBIDWABPROF

BIDKUM
1	SUBBAGRENMIN
2	SUBBIDSUNLUHKUM
3	SUBBIDBANKUM

BID TIK
1	SUBBAGRENMIN
2	SUBBIDTEKKOM
3	SUBBIDTEKINFO

SPRIPIM
1	URRENMIN
2	URPRODOK
3	URBUNGKOL
4	URPAMWAL

SETUM
1	URRENMIN
2	SUBBAGBINSETTAKAH
3	SUBBAGSIPTAKA
4	URKANPOS

YANMA
1	URRENMIN
2	SUBBAGYANTOR
3	SUBBAGHARBANGLING
4	SUBBAGPAMKOLSIK

SPKT
1	URRENMIN
2	SIAGA SPKT

DITINTELKAM
1	SUBBAGRENMIN
2	BAGANALIS
3	SIYANMIN
4	SITEKINTEL
5	SISANDI
6	SUBDIT 1
7	SUBDIT 2
8	SUBDIT 3
9	SUBDIT 4
10	SUBDIT 5

DITRESKRIMUM
1	SUBBAGRENMIN
2	BAGBINOPSNAL
3	BAGWASSIDIK
4	SIDENT
5	SUBDIT 1
6	SUBDIT 2
7	SUBDIT 3
8	SUBDIT 4

DITRESKRIMSUS
1	SUBBAGRENMIN
2	BAGBINOPSNAL
3	BAGWASSIDIK
4	SIKORWAS PPNS
5	SUBDIT 1
6	SUBDIT 2
7	SUBDIT 3
8	SUBDIT 4
9	SUBDIT 5

DITRESNARKOBA
1	SUBBAGRENMIN
2	BAGIBINOPSNAL
3	BAGWASSIDIK
4	SUBDIT 1
5	SUBDIT 2
6	SUBDIT 3

DITBINMAS
1	SUBBAGRENMIN
2	BAGBINOPSNAL
3	SUBDITBINTIBSOS
4	SUBDITBINSATPAM/POLSUS
5	SUBDITBINPOLMAS
6	SUBDITBHABINKAMTIBMAS

DITSAMAPTA
1	SUBBAGRENMIN
2	BAGBINOPSNAL
3	SUBDITGASUM
4	SUBDITDALMAS
5	UNITPOLSATWA

DITLANTAS
1	SUBBAGRENMIN
2	BAGBINOPSNAL
3	SUBDITBINGAKKUM
4	SUBDITREGIDENT
5	SUBDITKAMSEL
6	SAT PJR

DITPAMOBVIT
1	BAGRENMIN
2	BAGBINOPSNAL
3	SUBDITWASTER
4	SUBDITWISATA
5	SUBDITVIP
6	SUBDITAUDIT

DITPOLAIRUD
1	SUBBAGRENMIN
2	BAGBINOPSNAL
3	SUBDITGAKKUM
4	SUBDITPATROLAIRUD
5	SUBDITFASHARKAN
6	KAPAL C2
7	KAPAL C3
8	KAPAL KERET
9	KAPAL RIB
10	KAPAL SHIFT TENDER
11	PESAWAT UDARA

DITTAHTI
1	SUBBAGRENMIN
2	SUBDITPAMTAH
3	SUBDITHARWATAH
4	SUBDITBARBUK

SATBRIMOB
1	BAGRENMIN
2	BAGOPS
3	SILOG
4	SIPROVOS
5	SI TIK
6	SIKESJAS
7	SIYANMA
8	SIINTEL
9	DEN GEGANA
10	SUBDEN (4)
11	YONPELOPOR (3)
12	KOMPI (4)

SPN
1	SUBBAGRENMIN
2	SUBBAGYANUM
3	URPROVOS
4	SUBBAGJARLAT
5	KORSIS
6	POLIKLINIK

BIDKEU
1	SUBBAGRENMIN
2	SUBBIDBIA DAN APK
3	SUBBIDDALKU

BIDDOKKES
1	SUBBAGRENMIN
2	SUBBIDDOKPOL
3	SUBBIDKESPOL
4	POLIKLINIK

RUMKIT
1	SUBBAGRENMIN
2	SUBBAGBINFUNG
3	SUBBAGWASINTERN
4	SUBBIDYANMEDDOKPOL
5	SUBBIDJANGMEDUM
TXT;

        // ── DATA SATWIL ──────────────────────────────────────────
        $dataSatwil = <<<'TXT'
POLRESTA BANDAR LAMPUNG
1	BAGOPS
2	BAGREN
3	BAGSDM
4	BAGLOG
5	SIWAS
6	SIPROPAM
7	SIKEU
8	SIUM
9	SIKUM
10	SIHUMAS
11	SIDOKKES
12	SPKT
13	SATINTELKAM
14	SATRESKRIM
15	SATRESNARKOBA
16	SATBINMAS
17	SATSAMAPTA
18	SATLANTAS
19	SATPAMOBVIT
20	SATPOLAIRUD
21	SATTAHTI
22	SITIK
23	POLSEK KEDATON
24	POLSUBSEKTOR RAJA BASA
25	POLSEK SUKARAME
26	POLSEK TKT
27	POLSEK TKB
28	POLSEK TBU
29	POLSEK TBS
30	POLSEK TBT
31	POLSEK PANJANG
32	KSKP PANJANG
33	POLSUBSEKTOR CITRA GARDEN
34	POLSEK KEMILING
35	POLSEK  TJNG SENANG

POLRES METRO
1	BAGOPS
2	BAGREN
3	BAGSDM
4	BAGLOG
5	SIWAS
6	SIPROPAM
7	SIHUMAS
8	SIKUM
9	SITIK
10	SIUM
11	SPKT
12	SATINTELKAM
13	SATRESKRIM
14	SATRESNARKOBA
15	SATBINMAS
16	SATSAMAPTA
17	SATLANTAS
18	SATTAHTI
19	SIKEU
20	SIDOKKES
21	POLSEK METRO UTARA
22	POLSEK METRO BARAT
23	POLSEK METRO TIMUR
24	POLSEK METRO SELATAN
25	POLSEK METRO PUSAT

POLRES LAMPUNG SELATAN
1	BAGOPS
2	BAGREN
3	BAGSDM
4	BAGLOG
5	SIWAS
6	SIPROPAM
7	SIHUMAS
8	SIKUM
9	SITIK
10	SIUM
11	SPKT
12	SATINTELKAM
13	SATRESKRIM
14	SATRESNARKOBA
15	SATBINMAS
16	SATSAMAPTA
17	SATLANTAS
18	SATPAMOBVIT
19	SATPOLAIRUD
20	SATTAHTI
21	SIKEU
22	SIDOKKES
23	POLSEK NATAR
24	POLSEK TJ BINTANG
25	POLSEK KALIANDA
26	POLSEK KATIBUNG
27	POLSEK SIDOMULYO
28	POLSEK PENENGAHAN
29	POLSEK PALAS
30	POLSEK KSKP BAKAUHENI
31	POLSEK CANDIPURO
32	POLSEK SERAGI
33	POLSEK MERBAU MATARAM
34	POLSEK JATI AGUNG
35	POLSUBSEKTOR B. RADEN INTAN

POLRES LAMPUNG UTARA
1	BAGOPS
2	BAGREN
3	BAGSDM
4	BAGLOG
5	SIWAS
6	SIPROPAM
7	SIHUMAS
8	SIKUM
9	SITIK
10	SIUM
11	SPKT
12	SATINTELKAM
13	SATRESKRIM
14	SATRESNARKOBA
15	SATBINMAS
16	SATSAMAPTA
17	SATLANTAS
18	SATPAMOBVIT
19	SATPOLAIRUD
20	SATTAHTI
21	SIKEU
22	SIDOKKES
23	POLSEK BUKIT KEMUNING
24	POLSEK SUNGKAI SELATAN
25	POLSEK ABUNG BARAT
26	POLSEK ABUNG SELATAN
27	POLSEK ABUNG TIMUR
28	POLSEK SUNGKAI UTARA
29	POLSEK TANJUNG RAJA
30	POLSEK KOTABUMI UTARA
31	POLSEK ABUNG SEMULI
32	POLSEK ABUNG TENGAH
33	POLSEK MUARA SUNGKAI
34	POLSEK SUNGKAI JAYA
35	POLSEK ABUNG SURAKARTA
36	POLSEK BUNGA MAYANG
37	POLSEK KOTABUMI KOTA
38	POLSUBSEKTOR ABUNG TINGGI
39	POLSUBSEKTOR LUBUK RUKAM
40	POLSUBSEKTOR MULYO REJO
41	POLSUBSEKTOR PAPAN REJO
42	POLSUBSEKTOR CABANG EMPAT
43	POLSUBSEKTOR ABUNG KUNANG
44	POLSUBSEKTOR ABUNG PEKURUN

POLRES LAMPUNG BARAT
1	BAGOPS
2	BAGREN
3	BAGSDM
4	BAGLOG
5	SIWAS
6	SIPROPAM
7	SIHUMAS
8	SIKUM
9	SITIK
10	SIUM
11	SPKT
12	SATINTELKAM
13	SATRESKRIM
14	SATRESNARKOBA
15	SATBINMAS
16	SATSAMAPTA
17	SATLANTAS
18	SATPOLAIRUD
19	SATTAHTI
20	SIKEU
21	SIDOKKES
22	SATPAMOBVIT
23	POLSEK SUMBER JAYA
24	POLSEK SEKINCAU
25	POLSEK BANDAR NEGERI SUOH
26	POLSEK BALIK BUKIT
27	POLSUBSEKTOR WAY TENONG

POLRES TANGGAMUS
1	BAGOPS
2	BAGREN
3	BAGSDM
4	BAGLOG
5	SIWAS
6	SIPROPAM
7	SIHUMAS
8	SIKUM
9	SITIK
10	SIUM
11	SPKT
12	SATINTELKAM
13	SATRESKRIM
14	SATRESNARKOBA
15	SATBINMAS
16	SATSAMAPTA
17	SATLANTAS
18	SATPAMOBVIT
19	SATPOLAIRUD
20	SATTAHTI
21	SIKEU
22	SIDOKKES
23	POLSEK SEMAKA
24	POLSEK WONOSOBO
25	POLSEK KOTA AGUNG
26	POLSEK LIMAU
27	POLSEK SUMBEREJO
28	POLSEK PULAU PANGGUNG
29	POLSEK TALANG PADANG
30	POLSEK PEMATANG SAWA
31	POLSEK CUKUH BALAK
32	POLSEK PUGUNG
33	POLSUBSEKTOR NYAM
34	POLSUBSEKTOR KELUMBAYAN
35	POLSUBSEKTOR BULOK

POLRES TULANG BAWANG
1	BAGOPS
2	BAGREN
3	BAGSDM
4	BAGLOG
5	SIWAS
6	SIPROPAM
7	SIHUMAS
8	SIKUM
9	SITIK
10	SIUM
11	SPKT
12	SATINTELKAM
13	SATRESKRIM
14	SATRESNARKOBA
15	SATBINMAS
16	SATSAMAPTA
17	SATLANTAS
18	SATPAMOBVIT
19	SATPOLAIRUD
20	SATTAHTI
21	SIKEU
22	SIDOKKES
23	POLSEK MENGGALA
24	POLSEK GUNUNG TERANG
25	POLSEK BANJAR AGUNG
26	POLSEK PENAWARTAMA
27	POLSEK RAWA JITU S
28	POLSEK GEDUNG AJI
29	POLSEK RAWA PITU
30	POLSUBSEKTOR BANJAR AGUNG
31	POLSUBSEKTOR GEDUNG MENENG

POLRES LAMPUNG TIMUR
1	BAGOPS
2	BAGREN
3	BAGSDM
4	BAGLOG
5	SIWAS
6	SIPROPAM
7	SIHUMAS
8	SIKUM
9	SITIK
10	SIUM
11	SPKT
12	SATINTELKAM
13	SATRESKRIM
14	SATRESNARKOBA
15	SATBINMAS
16	SATSAMAPTA
17	SATLANTAS
18	SATPOLAIRUD
19	SATTAHTI
20	SIKEU
21	SIDOKKES
22	POLSEK SUKADANA
23	POLSEK LABUHAN MARINGGAI
24	POLSEK PEKALONGAN
25	POLSEK PURBOLINGGO
26	POLSEK RAMAN UTARA
27	POLSEK METRO KIBANG
28	POLSEK SEKAMPUNG
29	POLSEK BATANG HARI
30	POLSEK WAY JEPARA
31	POLSEK JABUNG
32	POLSEK SEKAMPUNG UDIK
33	POLSEK PASIR SAKTI
34	POLSEK WAWAY KARYA
35	POLSEK MELINTING
36	POLSEK GUNUNG PELINDUNG
37	POLSEK MATARAM BARU
38	POLSEK BANDAR SRIBHAWONO
39	POLSEK BATANG HARI NUBAN
40	POLSEK LABUHAN RATU
41	POLSEK WAY BUNGUR
42	POLSEK BUMI AGUNG
43	POLSEK MARGA TIGA
44	POLSEK BRAJA SELEBAH
45	POLSEK MARGA SKMPG
46	POLSUBSEKTOR GIRI MULYO
47	POLSUBSEKTOR SIDOREJO

POLRES WAY KANAN
1	BAGOPS
2	BAGREN
3	BAGSDM
4	BAGLOG
5	SIWAS
6	SIPROPAM
7	SIHUMAS
8	SIKUM
9	SITIK
10	SIUM
11	SPKT
12	SATINTELKAM
13	SATRESKRIM
14	SATRESNARKOBA
15	SATBINMAS
16	SATSABHARA
17	SATLANTAS
18	SATTAHTI
19	SIKEU
20	SIDOKKES
21	POLSEK BLAMBANGAN UMPU
22	POLSEK BARADATU
23	POLSEK KASUI
24	POLSEK BANJIT
25	POLSEK PAKUAN RATU
26	POLSEK BUAY BAHUGA
27	POLSEK WAY TUBA
28	POLSEK GUNUNG LABUHAN
29	POLSEK REBANG TANGKAS
30	POLSEK NEGARA BATIN
31	POLSEK NEGERI BESAR
32	POLSEK BUMI AGUNG
33	POLSUBSEKTOR NEGERI AGUNG

POLRES LAMPUNG TENGAH
1	BAGOPS
2	BAGREN
3	BAGSDM
4	BAGLOG
5	SIWAS
6	SIPROPAM
7	SIHUMAS
8	SIKUM
9	SITIK
10	SIUM
11	SPKT
12	SATINTELKAM
13	SATRESKRIM
14	SATNARKOBA
15	SATBINMAS
16	SATSAMAPTA
17	SATLANTAS
18	SATTAHTI
19	SIKEU
20	SIDOKKES
21	POLSEK TERBANGGI BESAR
22	POLSEK PADANG RATU
23	POLSEK GUNUNG SUGIH
24	POLSEK TRIMURJO
25	POLSEK PUNGGUR
26	POLSEK SEPUTIH RAMAN
27	POLSEK SEPUTIH BANYAK
28	POLSEK RUMBIA
29	POLSEK SEPUTIH SURABAYA
30	POLSEK KALIREJO
31	POLSEK BANGUN REJO
32	POLSEK SEPUTIH MATARAM
33	POLSEK WAY PENGUBUAN
34	POLSEK SELAGAI LINGGA
35	POLSEK TERUSAN NUNYAI
36	POLSEK ANAK RATU AJI
37	POLSEK BUMI RATU NUBAN
38	POLSUBSEKTOR KOTA GAJAH

POLRES MESUJI
1	BAGOPS
2	BAGREN
3	BAGSDM
4	BAGLOG
5	SIWAS
6	SIPROPAM
7	SIHUMAS
8	SIKUM
9	SITIK
10	SIUM
11	SPKT
12	SATINTELKAM
13	SATRESKRIM
14	SATRESNARKOBA
15	SATBINMAS
16	SATSAMAPTA
17	SATLANTAS
18	SATPAMOBVIT
19	SATPOLAIR
20	SATTAHTI
21	SIKEU
22	SIDOKES
23	POLSEK SIMPANG PEMATANG
24	POLSEK TANJUNG RAYA
25	POLSEK WAY SERDANG
26	POLSEK MESUJI TIMUR
27	POLSUBSEKTOR RAWA JITU UTARA
28	POLSUBSEKTOR MESUJI

POLRES PESAWARAN
1	BAGOPS
2	BAGREN
3	BAGSDM
4	BAGLOG
5	SIHUMAS
6	SIKUM
7	SIDOKKES
8	SIWAS
9	SIPROPAM
10	SIKEU
11	SITIK
12	SIUM
13	SPKT
14	SATINTELKAM
15	SATRESKRIM
16	SATRESNARKOBA
17	SATBINMAS
18	SATSAMAPTA
19	SATLANTAS
20	SATPAMOBVIT
21	SATTAHTI
22	SATPOLAIR
23	POLSEK GEDONG TATAAN
24	POLSEK KEDONDONG
25	POLSEK PADANG CERMIN
26	POLSEK TEGINENENG
27	POLSUBSEKTOR WAY LIMA
28	POLSUBSEKTOR NEGERI KATON

POLRES PRINGSEWU
1	BAGOPS
2	BAGREN
3	BAGSDM
4	BAGLOG
5	SIWAS
6	SIPROPAM
7	SIKEU
8	SIUM
9	SPKT
10	SATINTELKAM
11	SATRESKRIM
12	SATRESNARKOBA
13	SATBINMAS
14	SATSABHARA
15	SATLANTAS
16	SATTAHTI
17	SITIK
18	SIKUM
19	SIDOKKES
20	SIHUMAS
21	POLSEK PRINGSEWU KOTA
22	POLSEK PAGELARAN
23	POLSEK SUKOHARJO
24	POLSEK GADINGREJO
25	POLSEK PARDASUKA
26	POLSUBSEKTOR AMBARAWA
27	POLSUBSEKTOR BANYUMAS
28	POLSUBSEKTOR ADILUWIH
29	POLSUBSEKTOR PAGELARAN UTARA

POLRES TULANG BAWANG BARAT
1	BAGOPS
2	BAGREN
3	BAGSDM
4	BAGLOG
5	SIWAS
6	SIPROPAM
7	SIHUMAS
8	SIKUM
9	SITIK
10	SIUM
11	SPKT
12	SATINTELKAM
13	SATRESKRIM
14	SATRESNARKOBA
15	SATBINMAS
16	SATSABHARA
17	SATLANTAS
18	SATTAHTI
19	SIKEU
20	SIDOKKES
21	POLSEK TUBA TENGAH
22	POLSEK TUMIJAJAR
23	POLSEK GUNUNG AGUNG
24	POLSEK LAMBU KIBANG
25	POLSUBSEKTOR WAY KENANGA
26	POLSUBSEKTOR TUJOK

POLRES PESISIR BARAT
1	BAGOPS
2	BAGREN
3	BAGSDM
4	BAGLOG
5	SIWAS
6	SIPROPAM
7	SIHUMAS
8	SIKUM
9	SITIK
10	SIUM
11	SPKT
12	SATINTELKAM
13	SATRESKRIM
14	SATRESNARKOBA
15	SATBINMAS
16	SATSAMAPTA
17	SATLANTAS
18	SATPOLAIRUD
19	SATTAHTI
20	SIKEU
21	SIDOKKES
22	SATPAMOBVIT
23	POLSEK PESISIR TENGAH
24	POLSEK PESISIR UTARA
25	POLSEK PESISIR SELATAN
26	POLSEK BENGKUNAT
27	POLSUB SELENDANG MAYANG
TXT;

        $this->seedCategory($dataSatker, 'satker');
        $this->seedCategory($dataSatwil, 'satwil');
    }

    /**
     * Parse raw text data and seed records for one category.
     */
    private function seedCategory(string $rawText, string $tipeSatuan): void
    {
        $lines = explode("\n", $rawText);
        $currentParent = null;

        foreach ($lines as $line) {
            $line = trim($line);

            // Skip empty lines
            if ($line === '') {
                continue;
            }

            // Check if line starts with a number (sub-unit)
            if (preg_match('/^\d+\s+(.+)$/', $line, $matches)) {
                // This is a sub-unit
                $nama = trim($matches[1]);

                if ($currentParent) {
                    Satker::create([
                        'nama_satker'  => $nama,
                        'parent_id'    => $currentParent->id,
                        'tipe_satuan'  => $tipeSatuan,
                        'level'        => 'sub',
                    ]);
                }
            } else {
                // This is a parent (induk) unit
                $currentParent = Satker::create([
                    'nama_satker'  => $line,
                    'parent_id'    => null,
                    'tipe_satuan'  => $tipeSatuan,
                    'level'        => 'induk',
                ]);
            }
        }
    }
}
